<?php
return[
	'DOJI_WICK_MULTIPLIER' => 15,
	'DOJI_SHORTER_WICK_THRESHOLD' => 2,

	'MARUBOZU_MULTIPLIER' => 15,

    'HANGING_MAN_SHORTER_WICK_THRESHOLD' => 2,
    'HANGING_MAN_LONGER_WICK_THRESHOLD' => 70,

    'SHOOTING_STAR_SHORTER_WICK_THRESHOLD' => 2,
    'SHOOTING_STAR_LONGER_WICK_THRESHOLD' => 70,

    'SPINNING_TOP_BODY_THRESHOLD' => 30,
    'SPINNING_TOP_WICKS_DIFFERENCE_THRESHOLD' => 12,
];