<?php
return[
    'MARUBOZU_WICKS_THRESHOLD' => 5,
    'HAMMER_SHORTER_WICK_THRESHOLD' => 5,
    'HAMMER_LONGER_WICK_MULTIPLIER' => 2.5,
    'DOJI_SHORTER_WICK_THRESHOLD' => 2,
    'DOJI_WICK_MULTIPLIER' => 15,
    'SPINNING_TOP_WICKS_MULTIPLIER' => 5,
    'SPINNING_TOP_WICKS_DIFFERENCE_THRESHOLD' => 5,
];